### ISSUE TITLE
Generovanie nového XML v GUI

### ISSUE THREAD

**Issue by PearTomas** [TIS2022-FMFI/hot-air#118]
Po nahratí XML do aplikácie sa neprepíše, čiže originál sa zachová a vytvorí sa nové XML ktoré bude mať  v názve pridané "_temp_control" ?asi?

- ORIGINALNA SPRÁVA:
`"Chcem aby pri nacitani xml-ka sa povodny nezmenil ale vygenerovalo nove s indexom „_temp_control“ "`

**Comment by karkub** [comment]
@IvanBohman ak uz spustaju nejake svoje exe, neprida sa do toho bloku to nase (napr. pri tomto [Program_original.zip](https://github.com/TIS2022-FMFI/hot-air/files/10461114/Program_original.zip) )
