### ISSUE TITLE
Format udajov o fazach z xml

### ISSUE THREAD

**Issue by MarekDinka** [TIS2022-FMFI/hot-air#119]
idealny format pre udaje o fazach z xml by bol takyto:
List<AbstractMap.SimpleEntry<PhaseName, List<AbstractMap.SimpleEntry<ControllerID, Temp$Time>>>>

**Comment by pavelpetrovic** [comment]
Len cisto filozoficky ma zaujalo, ze preco zoznam mapovych entries a nie rovno mapa?

**Comment by MarekDinka** [comment]
S mapou by sa dalo vo vela pripadoch lepsie pracovat, vacsinou to ale je neusporiadana struktura a my potrebujeme ku fazam pristupovat chronologicky tak ako nastanu, dalo by sa asi vyuzit nejaku usporiadanu mapu, ale prislo mi to jednoduchsie takto.
