### ISSUE TITLE
XML zapisovanie súboru

### ISSUE THREAD

**Issue by PearTomas** [TIS2022-FMFI/hot-air#13]
Potrebujeme zistiť či by bolo možné si naše hodnoty teplôt ukladať do TestConrol XML config súboru.
To znamená že TestControl program nebude mať problém čítať súbor aj keď my doň zapíšeme nejaké svoje dáta o nastavovanej teplote. 
Či to bude ignorovať, alebo program ho nebude vedieť prečítať.

Ak to nebude problém všetky dáta si vieme uložiť do ich pôvodného XML súboru.
Ak s tým bude mať TestControl problém budeme si všetky dáta ukladať do nášho XML.

**Comment by IvanBohman** [comment]
Pozrel som sa na to, som zastancom myslienky, ze radsej nez upravovat ich xml-ko, bude lepsie tento subor len nacitat a spravit si nas vlastny, zrejme tiez xml (aby to bolo jednoducho editovtelne priamo) subor. A tam si uz vytiahneme len tie udaje, ktore su pre nas potrebne. Bude to prehladnejsie a lahsie sa s tym pracovat. 

Citanie xml-ka nie je v Jave ziaden problem, je na to tzv. DOM Parser vid link:
https://www.javatpoint.com/how-to-read-xml-file-in-java

Zaroven som si nastudoval ukazkove xml-ko, ktore nam zaslali, myslim ze som ho pochopil, a spisal z toho tagy ktore by nas mali zaujimat pri nacitavani.

Prikladam spominany rozpis tagov, hadam to na nieco  bude
[popis_struktury_xml.txt](https://github.com/TIS2022-FMFI/hot-air/files/9872065/popis_struktury_xml.txt)
