### ISSUE TITLE
podrobná špecifikácia vonkajších interfejsov

### ISSUE THREAD

**Issue by karkub** [TIS2022-FMFI/hot-air#14]
1. časť **návrhu**
> podrobne definovať aplikácie, súbory, zariadenia, s ktorými bude aplikácia komunikovať

**Comment by MarekDinka** [comment]
ak chceme robiť s tými 3 aplikáciami A, B, C tak bude treba komunikovať medzi nimi, teda musíme poslať údaje získané v aplikácií A<FrontEnd>(požadované teploty a údaje získané z ich xml programu) aplikácií B<BackEnd> aby ich vedela spracovať a organizovať aplikáciu C<Hardware> ktorá bude potom komunikovať(riadiť) priamo s fénom (tam tiež treba ďalšiu komunikáciu, čo bude ale vedieť skôr @PearTomas)
