### ISSUE TITLE
id duchadla

### ISSUE THREAD

**Issue by karkub** [TIS2022-FMFI/hot-air#175]
v GUI mam pripojene duchadlo
![image](https://user-images.githubusercontent.com/95253218/214391779-a745c69a-84eb-41c2-aa2d-392b9a2c7c59.png)

kliknem na stranku, vidim 
![image](https://user-images.githubusercontent.com/95253218/214391935-cb06c656-5f39-409c-b1e4-68a79bc05dba.png)

ked chcem zmenit ID
![image](https://user-images.githubusercontent.com/95253218/214392040-72d0118e-bcdf-4456-b16d-df1d91b3c20f.png)

zmenim ID na `id` (a ulozim ofc :)   no asi sa tam bere zle nejak ten ukoncovaci znak (?)
![image](https://user-images.githubusercontent.com/95253218/214392233-c4bfc18a-8cdb-4f23-8a78-04d809ccd670.png)

![image](https://user-images.githubusercontent.com/95253218/214392296-1fd4f86c-10c0-4dc5-b94a-f360a2ee77eb.png)

**Comment by PearTomas** [comment]
V main nie je nahratý súbor `preferences.h`
