### ISSUE TITLE
Nájsť fyzika kvôli vzorcu

### ISSUE THREAD

**Issue by MarekDinka** [TIS2022-FMFI/hot-air#2]
Na to aby sme vedeli efektívne (teda tak že "Fén" nebudeme stále vypínať a zapínať) zohrievať a hlavne udržiavať teplotu testovaného dielu, sa potrebujeme poradiť s niekým kto tomu rozumie.

**Comment by PearTomas** [comment]
Vec ktorú hladáme sa volá:
**_proportional derivative controller_**
