### ISSUE TITLE
Zmena komunikacie Server -> controller na UDP

### ISSUE THREAD

**Issue by MarekDinka** [TIS2022-FMFI/hot-air#209]
Mame 3 priority
1. Bez ack - posielam packety a necakam na ack
2. S ack - posielam packet a cakam na ack
3. TCP - posielam podla TCP

**Comment by karkub** [comment]
zo stretnutia 26.1.
- nastavenie servera ip a port, obmedzit na `10.2.x.x` , drzat sa dalej od `10.1.x.x`
