### ISSUE TITLE
spustanie projektu

### ISSUE THREAD

**Issue by karkub** [TIS2022-FMFI/hot-air#214]
@MarekDinka help please 🥹 

Server a GUI zapnute, arduino pripojene (aj v GUI).
Ked spustim projekt z promptu s EXECPP.exe, v GUI dostanem error
![image](https://user-images.githubusercontent.com/95253218/215295833-b24758ff-d055-4c2e-b244-801bfdf21506.png)

na serveri 
![image](https://user-images.githubusercontent.com/95253218/215295748-c85db7a3-70bc-4cce-8621-99e585d1f574.png)

a EXE vypise
![image](https://user-images.githubusercontent.com/95253218/215295903-1e4c8014-3269-4ce8-a93e-d320d415eea7.png)

**Comment by MarekDinka** [comment]
Obavam sa ze to vyzera skor ako problem s XML, cize to bude pre @IvanBohman

**Comment by MarekDinka** [comment]
ale musim povedat ze nerozumiem preco exception ktoru chce poslat GUI je null

**Comment by pavelpetrovic** [comment]
mne s zdá, že je to kombinovaný problém.
jednak nastala nejaká exception pri čítaní xml,
ale aj poslanie tej exception do gui sa nepodarilo.
nerozumiem prečo sa vyčítava cez ObjectInputStream,
keď sa tak neposiela, ale možno sa len nedívam na správne miesto.

**Comment by MarekDinka** [comment]
pri posielani Exception nastala velmi zvlastna vec, lebo vo vypise zo servera je cervenym null (hned pod prvou exception), toto je moj vypis v Server.java:224, kde je vypisana Message tej exception (preto tam aj potom dalej vyskocila null pointer exception a poslanie do GUI zlyhalo), problem je ze tato message nema dovod byt null, kedze co sa stane pred tym ako sa sem dostane 
je:
- server dostane xml a pokusi sa spustit novy projekt v EXEHandler.java:28, 
- ten zlyha na exception a teda sa dostaneme do EXEHandler.java:48, 
- tam sa exception zapise do loggeru a posle vsetkym pripojenym GUI na riadku 50,
- a teraz sme spet v Server.java:224, za celu tuto dobu nemala exception jediny dovod zmenit svoju message na null, co znamena ze null uz musela byt, to ale tiez nedava zmysel

**Comment by MarekDinka** [comment]
https://stackoverflow.com/questions/8613408/exception-message-is-null

**Comment by karkub** [comment]
o exception menej ale stale nejde 

GUI 
![image](https://user-images.githubusercontent.com/95253218/215343217-c2c9e592-1059-42bc-bec6-8be5a1d745ba.png)

server 
![image](https://user-images.githubusercontent.com/95253218/215343538-eb13c320-9908-46db-bbb8-ee4c84ecf696.png)

EXE 
![image](https://user-images.githubusercontent.com/95253218/215343467-d981894b-ea05-4e0f-9b53-29979e90eb9e.png)


[Program_id02.zip](https://github.com/TIS2022-FMFI/hot-air/files/10530357/Program_id02.zip)

**Comment by MarekDinka** [comment]
dufam ze to je to co som opravoval v tom quick fix

**Comment by karkub** [comment]
Po #216 
GUI 
![image](https://user-images.githubusercontent.com/95253218/215344377-d69939aa-e1c4-463c-a95a-99f671963463.png)

SERVER
![image](https://user-images.githubusercontent.com/95253218/215344371-b63c03e3-c43c-4429-aed5-2cbf45d5ca62.png)

EXE
![image](https://user-images.githubusercontent.com/95253218/215344419-6d403ba1-fd3b-4ee8-8b59-986a9f16115b.png)

**Comment by MarekDinka** [comment]
je tam novy pull request a po nom by to dufam mal byt uz iba Ivanou problem

**Comment by karkub** [comment]
Oki, vdaka Ivan.

@MarekDinka once again.. xd
Projekt uz teda ide spustit, aj sa zobrazi v tabe projektov, **ale** k bloweru sa neprida nazov projektu. 

Co pride GUI zo servera
![image](https://user-images.githubusercontent.com/95253218/215544342-77cfb660-1ae1-43f5-a746-509f352aef93.png)

Server
![image](https://user-images.githubusercontent.com/95253218/215545054-73086249-d202-4e92-986c-6c6b03a6cbaf.png)

**Comment by karkub** [comment]
jooj 😢 ale stale nejde 😆
