### ISSUE TITLE
Prieskum možností komunikácie medzi aplikáciou servera a mikroprocesorom

### ISSUE THREAD

**Issue by MarekDinka** [TIS2022-FMFI/hot-air#22]
Potrebujeme nájsť spôsob ako objaviť v sieti všetky mikroprocesory ktoré ovládajú fény a dohodnúť sa ako s nimi budeme komunikovať

**Comment by PearTomas** [comment]
# UDP komunikácia

- spolu s @MarekDinka sme riešili problematiku objavovania dúchadiel na sieti.

## Ciel
- vymyslieť spôsob akým vieme objavovať (discover) nové dúchala bez nutnosti akejkoľvek konfigurácie mikroprocesora.
- systém musí byť spoľahlivý (reliability) aby za každých okolností sme vedeli objaviť nové zariadenie.

## možnosti
- zariadenie si sieťové pripojenie nakonfiguruje cez DHCP.

### dúchadlo ako Svale
- mikroprocesory by v pravidelných intervaloch posielali UDP broadcast packet na dopredu špecifikovanom porte.
 - server by tieto packety vždy prijal a naspäť by odpovedal TCP.
 - toto by ale zbytočne zahlcovalo sieť (Performance efficiency)
 
### server posiela broadcast
- Server posiela pravidelne brodcast na dopredu dohodnutom porte
- mikroprocesor čaká na tieto packety a spätne odpovedá na server cez TCP protokol

## Záver
- rozhodli sme sa použiť druhú možnosť 'server posiela broadcast'
- Test dokázal funkčnosť takejto komunikácie. Mikroprocesor vie počúvať a spracovať UDP packety.
## Nevyriešené
- mikroprocesor ešte nevie posielať TCP packety na server
