### ISSUE TITLE
Controller disconnected

### ISSUE THREAD

**Issue by karkub** [TIS2022-FMFI/hot-air#220]
Neviem, ci je to bug v ramci "simulacie" alebo bude chyba niekde inde, treba otestovat.

![image](https://user-images.githubusercontent.com/95253218/215621198-9c2cd6f9-83a1-477d-a62e-fc44024874c4.png)

![image](https://user-images.githubusercontent.com/95253218/215621295-1f022d84-4f7b-486f-b732-c306e609d8f8.png)

**Comment by karkub** [comment]
Cas kolko vydrzi arduino pripojene (v minutach, co asi nie je dobre):

Ked na nom nebezal projekt
![58BA3C73-2DEA-4AAD-B060-4875FCB3C710](https://user-images.githubusercontent.com/95253218/216184954-2e355695-8510-48b6-99c8-ab18416fcfb0.jpeg)

S projektom
![C7939CFF-0CE7-42BB-9F8F-BCA10A81ED89](https://user-images.githubusercontent.com/95253218/216190678-3de211c0-3a91-4f09-802e-d68f85ba2301.jpeg)

**Comment by MarekDinka** [comment]
je to nieco co evidujeme a jeden z dovodou na #209 a #210
