### ISSUE TITLE
plán implementácie

### ISSUE THREAD

**Issue by karkub** [TIS2022-FMFI/hot-air#26]
> v akom poradí sa budú implementovať, testovať a navzájom spájať jednotlivé komponenty.

**Comment by pavelpetrovic** [comment]
aktualny brainstorming:

<html><body>
<google-sheets-html-origin><style type="text/css"></style>

zostava urobit:
--
- spracovanie xml zakomponovat v GUI
- komunikator na strane GUI a zodpovedajuci komunikator na strane servra  - vyspecifkovat a implmentovat komunikaciu
- logovanie pripravit rozhranie a potom implementovat, dat pozor aj na logovanie vsetkych vynimiek
- spravca beziacich projektov
- riadic konkretneho projektu
- komunikacia mikrokontrolera a servra
- logovanie teplôt
- zobrazovaniu stavu spojit s prijatymi hodnotami
- konfigurovanie jednocipaku
- prepojenie vyhladavania duchadiel so strankou statusov
- safe shutdown
- simulacia procesu bez duchadiel


</body>
</html>
