### ISSUE TITLE
UML state alebo UML sequence diagram

### ISSUE THREAD

**Issue by MarekDinka** [TIS2022-FMFI/hot-air#27]

**Comment by karkub** [comment]
2. a 3. sipka medzi Servrom a Duchadlami dat vyssie a potiahnut cerveny ramcek az za server. (+ este na podobnych miestach)
![Screenshot from 2023-02-19 20-39-01](https://user-images.githubusercontent.com/95253218/219971091-14579a89-3ea4-4292-b7da-978deea87c08.png)
