### ISSUE TITLE
Zariadenie pre komunikáciu s ventilátorom

### ISSUE THREAD

**Issue by PearTomas** [TIS2022-FMFI/hot-air#3]
Potrebujeme zistiť akým zariadením by sme vedeli komunikovať s ventilátorom.
Dostupná infraštruktúra LAN sieť.
Možnosti komunikácie:

> RaspberryPi (aktuálne nedostupné v obchodoch)

>  [Arduino s Ethernet shield](https://www.aliexpress.com/wholesale?catId=0&initiative_id=AS_20221005124844&SearchText=ethernet+shield+arduino&spm=a2g0o.productlist.1000002.0)

>  [ESP32 s Ethernet shield](http://www.wireless-tag.com/portfolio/wt32-eth01/)

> natiahnúť novú infraštruktúru, jedno centrálne RPi a káblom pripojiť každý fén na ovládanie.

**Comment by PearTomas** [comment]
Kúpené (na vlastné náklady) 
[ESP32 s Ethernet shield](http://www.wireless-tag.com/portfolio/wt32-eth01/)
Čakám pokiaľ príde. 
Otestovať #12

**Comment by pavelpetrovic** [comment]
Jedna vec ma trochu znepokojuje - ako majú zabezpečené vetranie tých priestorov. Ak to dúchadlo bude kúriť takouto pekelnou teplotou, tak sa tá elektronika upečie - bežná teplota, pri ktorej elektronika funguje je -40°C po +85°C a aj tam by bolo dobré mať nejakú rezervu. Skontrolujte, prosím, so zadávateľom, že vedia garantovať tieto podmienky - snáď áno, ale overte to a tiež to dajte do Katalógu požiadaviek, napr. v 2.4.

So zariadením pri testoch bude potom treba pracovať veľmi opatrne, lebo Vás to môže doslova upiecť za živa. Neviem, či si pamätám dobre, ale dúfam, že Vám neplánujú jedno také dúchadlo požičať - v takom prípade budem musieť byť pri všetkých testoch, ale neodporúčam to, lepšie bude chodiť to testovať iba ku nim do fabriky. Raz to tam bude treba ísť odskúšať, keď budeme mať zostrojený prototyp elektroniky na riadenie (prevodník je už na Slovensku, tak čoskoro ho snáď budeme mať) a potom až testovať, keď bude protyp celého softvéru hotový.

V manuále sa píše o "open loop" vs. "closed loop". Tým sa myslí to, že open loop je riadenie výkonu bez spätnej väzby (resp. s vlastnou spätnou väzbou pomocou externej tepelnej sondy a vlastným riadením) a closed loop je uzavretá slučka - čo znamená, že dúchadlo si samé meria teplotu vystupujúceho vzduchu a reguluje sa tak, aby teplota bola požadovaná. Funguje to aj pri ručnom riadení aj pri riadení cez pripojené zariadenie.

Myslím si, že bude lepšie využíať tú zabudovanú reguláciu - potom nemusíte riešiť PD regulátor. Pochybujem, že nejakou inou sondou zmerajú nejakú inú teplotu, keď sa na to bude fučať teplým vzduchom, tak ona bude ukazovať teplotu toho vzduchu aj tak.
Prosím overte to so zadávateľom.

Tu je pekné video o nastavovaní toho zariadenia: https://www.youtube.com/watch?v=5CqDe9RxYzE 
Pridajte ho, prosím, tiež do KP do referencii.

**Comment by PearTomas** [comment]
Keď sme tam boli tak v testovacom priestore sa normálne pochybujú pracovníci bez špecialných odevov. Tak že teplota nebude presahovať teplotu viac ako 40˚C. Pre istotu sa na to ale opýtame. 

Áno dúchadlo nám zapožičajú. Myslím si že pri dodržaní všetkých bezpečnostných opatrení písaných v HOTWIND_SYSTEM_datasheet.pdf a zvýšenej opatrnosti sa nám nemôže nič stať.

Zadávateľ chce riešiť ovládanie cez open loop, pretože closed loop spätná väzba im nevyhovuje.
Musíme to pridať do KP.

**Comment by pavelpetrovic** [comment]
poslušne hlásim, že modul 

DFR0971 2-Channel I2C to 0-10V DAC Module x 1
https://www.dfrobot.com/product-2613.html
https://wiki.dfrobot.com/SKU_DFR0971_2_Channel_I2C_0_10V_DAC_Module

Úspešne dorazil. Otestoval som ho - pripojil som ho k Arduinu a voltmetrom overil, že oba kanály sa dajú pekne
riadiť v rozsahu 0-10 V (bez ďalšieho napájania - stačí 5V z Arduina - resp. iného jednočipáku).

Keď budete mať tú komunikáciu s ethernetom, tak s tým dojdite a vyskúšame spraviť jednoduchý
testovací program a potom s tým zájdem s niekým alebo sám do fabriky to otestovať, že to dúchadlo
riadi ako potrebujete.

[dac.zip](https://github.com/TIS2022-FMFI/hot-air/files/9834366/dac.zip)
![IMG_20221021_003429](https://user-images.githubusercontent.com/13798920/197072434-bb5d1bd9-d045-42fe-9395-0c1fdd32a105.jpg)

**Comment by PearTomas** [comment]
Podarilo sa mi rozbehať komunikáciu z [WT32-ETH01](http://www.wireless-tag.com/portfolio/wt32-eth01/) cez USB2TTL prevodník.
ESP32 som úspešne flashol.
Chip LAN8720 funguje krásne. Používam knižnicu [WebServer_WT32_ETH01](https://github.com/khoih-prog/WebServer_WT32_ETH01).
z example som rozbehal základný web server. 

### Ping test
- testované 100 krát
- cez jeden switch (nie link-local)

| Bytes |min (ms)|average (ms)|max (ms)|packet loss (%)|
| :---- | :------- | :-------| :-------| :-------|
| `64` | `0.762` | `0.816`|`1.303`|`0`|
| `1024` | `1.172` | `1.216`|`1.298`|`0`|

### Meranie teploty čipom MAX6675
- Použil som knižnicu [MAX6675-library](https://github.com/adafruit/MAX6675-library)
- Obávam sa o presnosť merania.

#### Fotka web rozhrania a konzoly pri 2˚C
![Web rozhrania a konzola 2˚C](https://user-images.githubusercontent.com/47124922/197421248-cb2634a3-daaa-41c9-95d1-c702e7549ba9.png)

#### Fotka web rozhrania a konzoly pri 60˚C
![Web rozhrania a konzola 60˚C](https://user-images.githubusercontent.com/47124922/197421395-0fbe0e5f-fe48-41cd-a901-8eb79f9b5139.png)

- Reakčná doba teplomera z 2˚C na 60˚C boli necelé 3sek.

### Celkové zapojenie
![Celkové zapojenie WT32-ETH01 spolu s MAX6675](https://user-images.githubusercontent.com/47124922/197421455-ed8ee218-157d-43be-b370-e47a1a72bc40.jpg)
