### ISSUE TITLE
Pripraviť načítanavie vstupného XML súboru 

### ISSUE THREAD

**Issue by PearTomas** [TIS2022-FMFI/hot-air#38]

**Comment by karkub** [comment]
poznamky zo stretnutia 5.1.
- [ ] Ked sa nahráva XML do GUI prepisovať cestu k EXE podla aktualnej v GUI  
- [ ] Jedno xml = jeden stôl a moze byt pre viac ako dve dúchadlá  
- [ ] Exe v xml sa spusta tak ze tam je cesta k bat/exe a potom ako parameter cesta k xml bez percent 
- [ ] Exe iba s jedným parametrom  
- [ ] Obsahu v measurements sa nema meniť nazov, prida sa id a teplota do názvu measurements a to bude platit pre cely obsah v measurements  
- [ ] pridanie do tagu v tvare #id@teplota

**Comment by karkub** [comment]
Blokom v measurement sa zmenili nazvy

**Comment by pavelpetrovic** [comment]
z poslednej návštevy 
[F.zip](https://github.com/TIS2022-FMFI/hot-air/files/10524279/F.zip)

**Comment by pavelpetrovic** [comment]
mozno by namiesto toho dolara mohlo byt trojciferne cislo fazy.
000, 001, 002, ...
keby to nahodou restartli, aby sa to chytilo na spravnu fazu (a zalogovalo tu situaciu)
