### ISSUE TITLE
Vytvoriť katalóg požiadaviek

### ISSUE THREAD

**Issue by karkub** [TIS2022-FMFI/hot-air#4]
treba vytvoriť katalog

**Comment by pavelpetrovic** [comment]
par pripomienok v komentaroch v subore

[Katalog poziadaviek_s_komentarmi.docx](https://github.com/TIS2022-FMFI/hot-air/files/9768157/Katalog.poziadaviek_s_komentarmi.docx)

**Comment by karkub** [comment]
_update_ podla pripomienok zadavatela

> bezpecnostne napatie
> beta verzia aplikacie
