### ISSUE TITLE
Vytváranie logovacieho komponentu servera 

### ISSUE THREAD

**Issue by PearTomas** [TIS2022-FMFI/hot-air#43]

**Comment by karkub** [comment]
pouzivatel si bude moct nastavit v akej pravidelnosti chce logovat aktuálnu teplotu detekovanú pripojeným teplomerom do súboru pre možnosť kontroly (?)

**Comment by pavelpetrovic** [comment]
V KP je síce napísané "podľa nastavenia používateľa" , ale keby to bolo aj s maximálnou frekvenciou nap. každú sekundu, tak to podľa mňa až tak veľa dát nevyrobí, ale pamätám sa, že sme sa o tom rozprávali a niekto z Vás to nastavenie chcel mať.

druhá vec je koľko tých súborov má byť a myslím, že sme sa dohodli "per projekt", čiže všetky dúchadlá z toho istého projektu v jednom súbore.

**Comment by karkub** [comment]
budeme logovat

informácie o udalostiach formátu
`aktualny_cas(YYYY-MM-DD HH:MM:SS),meno_projektu,správa `
- [ ] exceptions -> pri parsovani (a ine)

informácie o teplotach formátu
`aktualny_cas(YYYY-MM-DD HH:MM:SS),nazov_fazy,id_duchadla1,aktualna_teplota, id_duchadla2,aktualna_teplota ` 
- [ ] teplotu

**Comment by karkub** [comment]
Temperature logs budeme ukladat tam kde je ulozeny xml, ktory spustame
