### ISSUE TITLE
Úprava vizuálu GUI aplikácie do finálnej podoby

### ISSUE THREAD

**Issue by PearTomas** [TIS2022-FMFI/hot-air#44]

**Comment by karkub** [comment]
asi uz hotovo

**Comment by karkub** [comment]
poznamky zo stretnutia 5.1.

- [ ] Graf do GUI, mby tak ze sa klikne na zobraz graf a otvorí sa nove okno s grafom 
- [ ] v bloweroch staci vypisovat id (s preklikom na config stranku), current temp, target temp, project name, stop btn
- [ ] Stop btn na projekty  
- [ ] ked sa stlaci stop bnt (okrem stop all) objavi sa potvrdzovacie okno ci ho naozaj chce zastavit
- [ ] keď stačia stop pri dúchadle duchadlo sa zastaví (server pošle 0°C) Zároveň vedľa dúchadlá sa dá výkričník (to znamená že je dúchadlo zablokované {ignoruje všetky požiadavky na ohrev (server aj stránka)}) ak sa na výkričník klikne dúchadlo sa odomkne a začne znova počúvať na teploty. 
- [ ] nejake upozornenie ak je vela logov teplot projektov (nad 100 / starsie ako mesiac ...) ci ich mozme zmazat

**Comment by karkub** [comment]
error pri tvorbe grafu 
![image](https://user-images.githubusercontent.com/95253218/214437788-baa1dbea-ce4a-4027-978b-865429431592.png)
