### ISSUE TITLE
Testovanie aplikácie a validácia podľa katalógu požidaviek 

### ISSUE THREAD

**Issue by PearTomas** [TIS2022-FMFI/hot-air#45]

**Comment by pavelpetrovic** [comment]
Dnes prišli ďalšie tri WT32-ETH01, takže ak spravíte v kontroleri ten simulačný režim (namiesto posielania údajov do DAC nič a namiesto čítanie hodnoty z teplomera bude generovať teplotu so zotrvačnosťou podľa nastaveného výkonu dúchadla), tak sa to bude dať aj prakticky testovať aj ako keby bežali dva projekty, každý by riadil dve dúchadlá. Ak by ste s tou simuláciou potrebovali pomoc, dajte vedieť, rád to tam dopíšem...

**Comment by karkub** [comment]
done -> Testovanie Ovladania duchadla #196
