### ISSUE TITLE
Vytvorit Testovacie Scenare

### ISSUE THREAD

**Issue by IvanBohman** [TIS2022-FMFI/hot-air#46]
nenahradzaju testovanie, sluzia iba na overenie, ze vsetko je implementovane a hotove

**Comment by karkub** [comment]
https://liveuniba-my.sharepoint.com/:w:/g/personal/hruskovic3_uniba_sk/EYpOcu86HL9DoocJh3x2VR4BaGaAHEhsu29ABVphczzMDw?e=SjMhlT

**Comment by karkub** [comment]
treba upravit do finalnej podoby
