### ISSUE TITLE
Konfigurovateľný port pre aplikácie.

### ISSUE THREAD

**Issue by PearTomas** [TIS2022-FMFI/hot-air#55]
### Mať možnosť nakonfigurovať na akých portoch budú programy (GUI, EXE, Server a dúchadlá ) počúvať.

- [x] EXE posielať ako parameter ?
- [x] SERVER konfiguračný súbor ?
- [x] GUI možnosť zmeny v nastaveniach ?
- [x] DÚCHADLO možnosť zmeny cez web rozhranie, port zapisaný v EEPROM.

**Comment by PearTomas** [comment]
Každá aplikácia (EXE, SERVER, GUI, DÚCHADLO) musí mať možnosť zmeniť TCP PORT cez ktorý komunikujú.
Implementácia zmeny PORTU môžete spraviť podľa svojho najlepšieho vedomia a svedomia.

**Comment by karkub** [comment]
poznamky zo stretnutia 5.1.

- [ ] Kazdemu dúchadlu napevno priradíme IP adresu, navrhnúť rozumnú konfiguráciu 
- [ ] Ak vypadne sieť tak vypnúť testovanie po 100sekund  
- [ ] Ked sa preruší testovanie a znova spustí dat voľbu ci pokracovat kde to spadlo alebo zacne odznova 
- [ ] Ked sa pauzne projekt (v testcontrol), dúchadlá držia teplotu, ptm sa resumne a pokračuje sa v testovani  
- [ ] Ked server pošle na dúchadlo teplotu hreje stale dokiaľ sa nevypne / nepadne sieť / nepríde nova požiadavka na teplotu 
- [ ] keď server pošle controlleru teplotu 0°C tak fuka na 50% stále 
- [ ] Na konci je 0 teplota 
- [ ] Ked klesne pod 30 treba 5min vychladnut
