### ISSUE TITLE
server -> GUI

### ISSUE THREAD

**Issue by karkub** [TIS2022-FMFI/hot-air#64]
GUI potrebuje ziskat zo servera:
-  pocet duchadiel
-  pocel projektov

**Comment by MarekDinka** [comment]
@karkub do hot-air/src/GUI/str/main/java/Communication som pridal classy ktore sa postaraju o komunikaciu so serverom #73, co potrebujem od teba je aby si si vytvorila instanciu ClientHandler a ona ma/bude mat vsetky metody ktore budu komunikovat so serverom a vracat ti informacie.
Co este potrebujem:
- trieda Client je thread ktory caka ci mu zo serveru pride Exception a nasledne ju potrebuje niekam poslat (riadok 155) 
- zatial som tam pridal este metodu na zmenu ID controllera ale predpokladam ze bude treba aj dalsie

**Comment by karkub** [comment]
@MarekDinka v src/GUI/src/main/java/GUI/GUI.java je funkcia na zobrazenie alert okien, ktora ma za parameter exception, ktora nastala. Pojde to zavolat z toho Clienta?

v GUIController su funkcie na .... , ktore treba este poriesit nejak aj so serverom
- [ ] skenovanie siete pre najdenie novych duchadiel
- [ ] zastavenie vsetkych duchadiel
- [ ] treba poriesit aj zastavenie jednotliveho duchadla ked sa stlaci prislusny button

Zo serveru potrebujem

- pre duchadla:
  - [ ] pocet duchadiel
  - [ ] ID
  - [ ] IP adresu
  - [ ] aktualnu teplotu
  - [ ] cielenu teplotu
  - [ ] projekt kam duchadlo patri -> name bud z tagu v xml (@IvanBohman ? ) alebo cez path 
 
- pre projekt:
  - [ ] meno projektu -> name bud z tagu v xml (@IvanBohman ? ) alebo cez path 
  - [ ] cas od zaciatku spustenia (ak to chceme zobrazovat ?)
  - [ ] aktualnu fazu, v ktorej sa projekt nachadza

**Comment by MarekDinka** [comment]
#81 Dorobil som tie funkcie v ClientHandler a nasiel som v GUIController pripravenu funkciu na sken duchadiel a zastavenie vsetkych, tak som tam dal taky navrh ako by to snad mohlo fungovat, dalej tam je funkcia getAllControllers() ktora ti vrati info ku vsetkym duchadlam zaobalene v classe (akurat som to este netestoval takze zatial to funguje hlavne teoreticky), ked chces nebol by problem dat to do tvojho Blower.java

**Comment by karkub** [comment]
poznamky zo stretnutia 5.1.
- [ ] Projekt name z tagu name nie z cesty

+ poriesit veci v #44

**Comment by karkub** [comment]
Vsetko funguje 🤞
