### ISSUE TITLE
Design web stránky pre konfiguráciu controllera

### ISSUE THREAD

**Issue by PearTomas** [TIS2022-FMFI/hot-air#68]
naprogramovať webovú stránku kde sa budú dať nastavovať parametre. 
- Nakoľko to nie je ani raz spomenuté v KP tak si to spravím podľa seba :sweat_smile: 
- Asi budem potrebovať pomôcť s CSS :snail:

**Comment by pavelpetrovic** [comment]
Podla mna staci trochu upravit tu, co tam uz mame, konkretne pridat tlacidlo SAVE TO EEPROM a aby pri otvoreni ukazala hodnoty, ktore boli ulozene v EEPROM. 

Ma to sice 320KB RAM, takze by tam mohlo byt aj zakodovane logo spolocnosti :D, ale najskor nech ten system funguje...

**Comment by karkub** [comment]
pridat moznost zmeny ID controllera

**Comment by PearTomas** [comment]
Nefunguje spoľahlivo.
